import { MenuItem } from '@/types/restaurant';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Dolma',
    nameKurdish: 'دۆڵمە',
    nameArabic: 'دولمة',
    category: 'appetizers',
    price: 13000,
    description: 'Grape leaves stuffed with rice, herbs, and spices',
    descriptionKurdish: 'گەڵای مێو پڕکراو بە برنج و گیا و بەهارات',
    descriptionArabic: 'ورق عنب محشي بالأرز والأعشاب والتوابل',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '2',
    name: 'Muhammara',
    nameKurdish: 'محمرة',
    nameArabic: 'محمرة',
    category: 'appetizers',
    price: 11000,
    description: 'Roasted red pepper and walnut dip with pomegranate molasses',
    descriptionKurdish: 'دیپی بیبەری سوور و گوێز بە دەبسی هەنار',
    descriptionArabic: 'صلصة الفلفل الأحمر المحمص والجوز مع دبس الرمان',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '3',
    name: 'Fattoush',
    nameKurdish: 'فتوش',
    nameArabic: 'فتوش',
    category: 'appetizers',
    price: 10000,
    description: 'Fresh salad with crispy pita chips, sumac, and lemon dressing',
    descriptionKurdish: 'زەڵاتەی تازە بە پارچە نانی وشک و سوماق و لیمۆ',
    descriptionArabic: 'سلطة طازجة مع رقائق الخبز المقرمشة والسماق وصلصة الليمون',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '4',
    name: 'Kurdish Meze Platter',
    nameKurdish: 'مەزە کوردی',
    nameArabic: 'طبق المزة الكردية',
    category: 'appetizers',
    price: 23000,
    description: 'Assorted appetizers including hummus, baba ghanoush, and pickles',
    descriptionKurdish: 'مەزەی جۆراوجۆر لەوانە حومس و بابا غەنووج و تورشی',
    descriptionArabic: 'مقبلات متنوعة تشمل الحمص وبابا غنوج والمخللات',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '5',
    name: 'Shorba',
    nameKurdish: 'شۆربا',
    nameArabic: 'شوربة',
    category: 'soups',
    price: 9000,
    description: 'Traditional Kurdish lentil soup with cumin and lemon',
    descriptionKurdish: 'شۆربای نیسکی کوردی بە زیرە و لیمۆ',
    descriptionArabic: 'شوربة العدس الكردية التقليدية مع الكمون والليمون',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '6',
    name: 'Dowjic',
    nameKurdish: 'دۆجیچ',
    nameArabic: 'دوجيج',
    category: 'soups',
    price: 10000,
    description: 'Yogurt-based soup with rice and herbs',
    descriptionKurdish: 'شۆربای ماستی بە برنج و گیا',
    descriptionArabic: 'شوربة الزبادي مع الأرز والأعشاب',
    image: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '7',
    name: 'Tikka Kebab',
    nameKurdish: 'تکە کەباب',
    nameArabic: 'تكة كباب',
    category: 'kebabs',
    price: 25000,
    description: 'Marinated lamb chunks grilled to perfection',
    descriptionKurdish: 'پارچە گۆشتی بەرخی مارینەیت کراو بە تەواوی برژاو',
    descriptionArabic: 'قطع لحم الضأن المتبلة المشوية بشكل مثالي',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '8',
    name: 'Shish Kebab',
    nameKurdish: 'شیش کەباب',
    nameArabic: 'شيش كباب',
    category: 'kebabs',
    price: 23000,
    description: 'Ground lamb and beef with Kurdish spices',
    descriptionKurdish: 'گۆشتی بەرخ و مانگای هاڕاو بە بەهاراتی کوردی',
    descriptionArabic: 'لحم الضأن والبقر المفروم مع التوابل الكردية',
    image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '9',
    name: 'Chicken Kebab',
    nameKurdish: 'کەبابی مریشک',
    nameArabic: 'كباب الدجاج',
    category: 'kebabs',
    price: 22000,
    description: 'Tender chicken marinated in yogurt and spices',
    descriptionKurdish: 'مریشکی نەرم مارینەیت کراو بە ماست و بەهارات',
    descriptionArabic: 'دجاج طري متبل بالزبادي والتوابل',
    image: 'https://images.unsplash.com/photo-1633945274309-2c8c2b0e3f0f?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '10',
    name: 'Mixed Grill',
    nameKurdish: 'کەبابی تێکەڵ',
    nameArabic: 'مشاوي مشكلة',
    category: 'kebabs',
    price: 34000,
    description: 'Combination of lamb, beef, and chicken kebabs',
    descriptionKurdish: 'تێکەڵەی کەبابی بەرخ و مانگا و مریشک',
    descriptionArabic: 'مزيج من كباب الضأن والبقر والدجاج',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '11',
    name: 'Biryani',
    nameKurdish: 'بریانی',
    nameArabic: 'برياني',
    category: 'rice-dishes',
    price: 21000,
    description: 'Fragrant rice with lamb, raisins, and almonds',
    descriptionKurdish: 'برنجی بۆنخۆش بە بەرخ و کشمیش و بادەم',
    descriptionArabic: 'أرز عطري مع لحم الضأن والزبيب واللوز',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '12',
    name: 'Qabuli Palaw',
    nameKurdish: 'قابلی پەلاو',
    nameArabic: 'قابلي بلاو',
    category: 'rice-dishes',
    price: 22000,
    description: 'Rice pilaf with carrots, raisins, and tender lamb',
    descriptionKurdish: 'برنجی پەلاو بە گەزەر و کشمیش و بەرخی نەرم',
    descriptionArabic: 'أرز بلاو مع الجزر والزبيب ولحم الضأن الطري',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '13',
    name: 'Kofta wa Ruz',
    nameKurdish: 'کوفتە و رز',
    nameArabic: 'كفتة ورز',
    category: 'rice-dishes',
    price: 19000,
    description: 'Meatballs in tomato sauce served over saffron rice',
    descriptionKurdish: 'کوفتە لە سۆسی تەماتە لەسەر برنجی زەعفەران',
    descriptionArabic: 'كرات اللحم في صلصة الطماطم تقدم فوق أرز الزعفران',
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '14',
    name: 'Bamia',
    nameKurdish: 'بامیە',
    nameArabic: 'بامية',
    category: 'stews',
    price: 18000,
    description: 'Okra stew with lamb in tomato sauce',
    descriptionKurdish: 'خۆراکی بامیە بە بەرخ لە سۆسی تەماتە',
    descriptionArabic: 'يخنة البامية مع لحم الضأن في صلصة الطماطم',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '15',
    name: 'Fasolia',
    nameKurdish: 'فاسۆلیا',
    nameArabic: 'فاصوليا',
    category: 'stews',
    price: 16000,
    description: 'Green bean stew with lamb and tomatoes',
    descriptionKurdish: 'خۆراکی لۆبیای سەوز بە بەرخ و تەماتە',
    descriptionArabic: 'يخنة الفاصوليا الخضراء مع لحم الضأن والطماطم',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '16',
    name: 'Tashreeb',
    nameKurdish: 'تەشریب',
    nameArabic: 'تشريب',
    category: 'stews',
    price: 21000,
    description: 'Lamb stew served over crispy bread with chickpeas',
    descriptionKurdish: 'خۆراکی بەرخ لەسەر نانی وشک بە نۆک',
    descriptionArabic: 'يخنة لحم الضأن تقدم فوق الخبز المقرمش مع الحمص',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '17',
    name: 'Naan Tandoori',
    nameKurdish: 'نانی تەندووری',
    nameArabic: 'خبز التندوري',
    category: 'breads',
    price: 4000,
    description: 'Fresh baked flatbread from the tandoor',
    descriptionKurdish: 'نانی تازە برژاو لە تەندوور',
    descriptionArabic: 'خبز مسطح طازج من التندور',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '18',
    name: 'Samoon',
    nameKurdish: 'سەموون',
    nameArabic: 'صمون',
    category: 'breads',
    price: 3000,
    description: 'Traditional Iraqi diamond-shaped bread',
    descriptionKurdish: 'نانی عێراقی بە شێوەی ئەڵماس',
    descriptionArabic: 'خبز عراقي تقليدي على شكل ماسة',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '19',
    name: 'Kleicha',
    nameKurdish: 'کلێچە',
    nameArabic: 'كليجة',
    category: 'breads',
    price: 6000,
    description: 'Sweet date-filled pastries',
    descriptionKurdish: 'شیرینی پڕکراو بە خورما',
    descriptionArabic: 'معجنات محشوة بالتمر الحلو',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '20',
    name: 'Baklava',
    nameKurdish: 'بەقلاوە',
    nameArabic: 'بقلاوة',
    category: 'desserts',
    price: 9000,
    description: 'Layers of phyllo with nuts and honey syrup',
    descriptionKurdish: 'چینەکانی فیلۆ بە گوێز و شەربەتی هەنگوین',
    descriptionArabic: 'طبقات من العجين الرقيق مع المكسرات وشراب العسل',
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '21',
    name: 'Halwa',
    nameKurdish: 'حەلوا',
    nameArabic: 'حلاوة',
    category: 'desserts',
    price: 7000,
    description: 'Sweet tahini-based dessert with pistachios',
    descriptionKurdish: 'شیرینی تاهینی بە پستە',
    descriptionArabic: 'حلوى الطحينة الحلوة مع الفستق',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '22',
    name: 'Kunafa',
    nameKurdish: 'کونافە',
    nameArabic: 'كنافة',
    category: 'desserts',
    price: 10000,
    description: 'Shredded phyllo with sweet cheese and syrup',
    descriptionKurdish: 'فیلۆی وردکراو بە پەنیری شیرین و شەربەت',
    descriptionArabic: 'عجين رقيق مبشور مع الجبن الحلو والشراب',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '23',
    name: 'Chai',
    nameKurdish: 'چای',
    nameArabic: 'شاي',
    category: 'drinks',
    price: 4000,
    description: 'Traditional Kurdish black tea',
    descriptionKurdish: 'چایی ڕەشی کوردی',
    descriptionArabic: 'شاي أسود كردي تقليدي',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '24',
    name: 'Ayran',
    nameKurdish: 'ئەیران',
    nameArabic: 'عيران',
    category: 'drinks',
    price: 5000,
    description: 'Refreshing yogurt drink with mint',
    descriptionKurdish: 'خواردنەوەی ماستی سەرینکەرەوە بە پونە',
    descriptionArabic: 'مشروب الزبادي المنعش مع النعناع',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '25',
    name: 'Fresh Pomegranate Juice',
    nameKurdish: 'ئاوی هەنار',
    nameArabic: 'عصير الرمان الطازج',
    category: 'drinks',
    price: 7000,
    description: 'Freshly squeezed pomegranate juice',
    descriptionKurdish: 'ئاوی هەناری تازە گوشراو',
    descriptionArabic: 'عصير رمان طازج معصور',
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '26',
    name: 'Soft Drinks',
    nameKurdish: 'خواردنەوەی گازدار',
    nameArabic: 'مشروبات غازية',
    category: 'drinks',
    price: 3000,
    description: 'Coca-Cola, Sprite, Fanta',
    descriptionKurdish: 'کۆکاکۆلا، سپرایت، فانتا',
    descriptionArabic: 'كوكاكولا، سبرايت، فانتا',
    image: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '27',
    name: 'Caesar Salad',
    nameKurdish: 'زەڵاتەی سیزەر',
    nameArabic: 'سلطة سيزر',
    category: 'salads',
    price: 12000,
    description: 'Crispy romaine lettuce with parmesan and Caesar dressing',
    descriptionKurdish: 'سەڵاتەی ڕۆمەین بە پەنیری پارمیزان و سۆسی سیزەر',
    descriptionArabic: 'خس روماني مقرمش مع بارميزان وصلصة سيزر',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '28',
    name: 'Greek Salad',
    nameKurdish: 'زەڵاتەی یۆنانی',
    nameArabic: 'سلطة يونانية',
    category: 'salads',
    price: 13000,
    description: 'Fresh vegetables with feta cheese and olives',
    descriptionKurdish: 'سەڵاتەی تازە بە پەنیری فێتا و زەیتوون',
    descriptionArabic: 'خضروات طازجة مع جبنة فيتا وزيتون',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '29',
    name: 'Grilled Salmon',
    nameKurdish: 'ماسی سەلمۆنی برژاو',
    nameArabic: 'سلمون مشوي',
    category: 'seafood',
    price: 28000,
    description: 'Fresh Atlantic salmon with lemon butter sauce',
    descriptionKurdish: 'ماسی سەلمۆنی تازە بە سۆسی کەرە و لیمۆ',
    descriptionArabic: 'سلمون أتلنتي طازج مع صلصة الزبدة والليمون',
    image: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '30',
    name: 'Shrimp Kebab',
    nameKurdish: 'کەبابی میگۆ',
    nameArabic: 'كباب الروبيان',
    category: 'seafood',
    price: 30000,
    description: 'Marinated jumbo shrimp grilled on skewers',
    descriptionKurdish: 'میگۆی گەورە مارینەیت کراو لەسەر سیخ برژاو',
    descriptionArabic: 'روبيان جامبو متبل مشوي على أسياخ',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '31',
    name: 'Double Apple Shisha',
    nameKurdish: 'شیشەی دابڵ ئەپڵ',
    nameArabic: 'شيشة تفاحتين',
    category: 'shisha',
    price: 22000,
    description: 'Premium double apple flavored shisha',
    descriptionKurdish: 'شیشەی تایبەت بە تامی دوو سێو',
    descriptionArabic: 'شيشة فاخرة بنكهة تفاحتين',
    image: 'https://images.unsplash.com/photo-1580933073521-dc49ac0d4e6a?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '32',
    name: 'Mint Shisha',
    nameKurdish: 'شیشەی پونە',
    nameArabic: 'شيشة نعناع',
    category: 'shisha',
    price: 22000,
    description: 'Refreshing mint flavored shisha',
    descriptionKurdish: 'شیشەی سەرینکەرەوە بە تامی پونە',
    descriptionArabic: 'شيشة منعشة بنكهة النعناع',
    image: 'https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '33',
    name: 'Turkish Coffee',
    nameKurdish: 'قاوەی تورکی',
    nameArabic: 'قهوة تركية',
    category: 'hot-drinks',
    price: 5000,
    description: 'Traditional Turkish coffee with cardamom',
    descriptionKurdish: 'قاوەی تورکی بە هێل',
    descriptionArabic: 'قهوة تركية تقليدية مع الهيل',
    image: 'https://images.unsplash.com/photo-1610889556528-9a770e32642f?w=400&h=300&fit=crop',
    available: true,
  },
  {
    id: '34',
    name: 'Espresso',
    nameKurdish: 'ئێسپرێسۆ',
    nameArabic: 'إسبريسو',
    category: 'hot-drinks',
    price: 5000,
    description: 'Rich Italian espresso',
    descriptionKurdish: 'ئێسپرێسۆی ئیتاڵی',
    descriptionArabic: 'إسبريسو إيطالي غني',
    image: 'https://images.unsplash.com/photo-1579992357154-faf4bde95b3d?w=400&h=300&fit=crop',
    available: true,
  },
];

export const CATEGORY_NAMES: Record<string, string> = {
  appetizers: 'Appetizers',
  soups: 'Soups',
  salads: 'Salads',
  kebabs: 'Kebabs',
  'rice-dishes': 'Rice Dishes',
  stews: 'Stews',
  seafood: 'Seafood',
  breads: 'Breads',
  desserts: 'Desserts',
  drinks: 'Cold Drinks',
  shisha: 'Shisha',
  'hot-drinks': 'Hot Drinks',
};
